/*
 * Universe.sh kourou API
 *
 * Universe.sh kourou API
 *
 * API version: 0.0.1
 * Contact: oss@universe.sh
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// MetricData struct for MetricData
type MetricData struct {
	Value int32 `json:"value,omitempty"`
	Time string `json:"time,omitempty"`
}
