/*
 * Universe.sh kourou API
 *
 * Universe.sh kourou API
 *
 * API version: 0.0.1
 * Contact: oss@universe.sh
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Preferences struct for Preferences
type Preferences struct {
	DefaultPermission string `json:"default-permission,omitempty"`
}
