/*
 * Universe.sh kourou API
 *
 * Universe.sh kourou API
 *
 * API version: 0.0.1
 * Contact: oss@universe.sh
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// AccountDefaultTeam struct for AccountDefaultTeam
type AccountDefaultTeam struct {
	Id string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
}
