/*
 * Universe.sh kourou API
 *
 * Universe.sh kourou API
 *
 * API version: 0.0.1
 * Contact: oss@universe.sh
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Invitation struct for Invitation
type Invitation struct {
	Id string `json:"id,omitempty"`
	InvitedBy InvitationInvitedBy `json:"invited_by,omitempty"`
	Team InvitationTeam `json:"team,omitempty"`
	User InvitationUser `json:"user,omitempty"`
	CreatedAt string `json:"created_at,omitempty"`
	UpdatedAt string `json:"updated_at,omitempty"`
}
