/*
 * Universe.sh kourou API
 *
 * Universe.sh kourou API
 *
 * API version: 0.0.1
 * Contact: oss@universe.sh
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// PoolLaunchSpecificationConfig struct for PoolLaunchSpecificationConfig
type PoolLaunchSpecificationConfig struct {
	Subnetwork string `json:"subnetwork,omitempty"`
	Template string `json:"template,omitempty"`
}
