/*
 * Universe.sh kourou API
 *
 * Universe.sh kourou API
 *
 * API version: 0.0.1
 * Contact: oss@universe.sh
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// Generic struct for Generic
type Generic struct {
	Error bool `json:"error,omitempty"`
	Message string `json:"message,omitempty"`
}
